# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  install:
    - bundle install
  run:
    - bundle exec jekyll serve
